### ISSUE TITLE
Give hound a trial run?

### ISSUE THREAD

**Issue by ericelliott** [cloverfield-tools/prod-module-boilerplate#37]
[houndci.com](https://houndci.com/)

**Comment by nkbt** [comment]
I'd recommend to use CircleCI. We had some research done recently for our main ecosystem on may main work and CircleCI is just awesome to say the least. I moved my personal projects there and super happy about it.

In our workflow it creates artifacts, calls Coveralls, creates reports. Then pushes artifacts to Bintray and so on.

See example of my personal project https://circleci.com/gh/in-flux/in-flux

**Comment by ericelliott** [comment]
Let's do that. HoundCI is just a cloud style checker. =)

**Comment by nkbt** [comment]
Will do

**Comment by nkbt** [comment]
Hound uses JSHint, which does not have full support for ES6. And actually we don't really need it since our codestyle is checked anyway. The problem with Travis, it does not have any artifacts stored, so you cannot see the results of those tests in the UI.

Today CircleCI has a major outage as a result of GitHub outage earlier. It works but very slow. Will add it later, when it starts working normally.
